image: milthorpe/comp1110-2021-s1-gitlab-ci:0.1.2

stages:
  - integrity
  - compliance
  - build
  - test

before_script:
  - export PATH_TO_FX=/usr/share/openjfx/lib
  - export JAVAFX_OPTIONS="--module-path $PATH_TO_FX"
  - export CP=src:/ass1/comp1110-ass1-tests.jar:/shared/junit-platform-console-standalone-1.7.0.jar
  - export JUNIT="java $JAVAFX_OPTIONS -jar /shared/junit-platform-console-standalone-1.7.0.jar --class-path $CP --disable-banner"

integrity:
  tags:
    - comp1110
  stage: integrity
  script:
    - python3 /validate.py --integrity comp1110-ass1

admin:
  tags:
    - comp1110
  stage: compliance
  script:
    - python3 /validate.py --schema https://cs.anu.edu.au/courses/comp1110/schemas/statement-of-originality.json ./originality.yml

build:
  tags:
    - comp1110
  stage: build
  script:
    - javac -encoding utf-8 $JAVAFX_OPTIONS -cp $CP src/comp1110/ass1/*.java
  artifacts:
    paths:
      - src/comp1110/ass1/*.class

task1:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.OneLetterBasicPhonemesTest
  allow_failure: true

task2:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.RemoveDoublesTest
  allow_failure: true

task3:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.MultiLetterBasicPhonemesTest
  allow_failure: true

task4:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.SyllablesTest
  allow_failure: true

task5:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.LastPhonemeSilentTest
  allow_failure: true

task6:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.SoftConsonantTest
  allow_failure: true

task7:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.BetweenTwoVowelsTest
  allow_failure: true

task8:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.VowelOrConsonantIYTest
  allow_failure: true

task9:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.LetterETest
  allow_failure: true

task10:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.ErEzTest
  allow_failure: true

task11:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.CondenseSyllablesTest
  allow_failure: true

## Local Variables:
## mode: yaml
## End:
